name: holomotion_train_isaaclab
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - mesalib
  - pip:
    - -r requirements/requirements_train_isaaclab.txt
    - -e ./thirdparties/SMPLSim
    - -e .
