# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: ppo
  - /robot: unitree/G1/23dof/23dof_training_v0_official_urdf
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_unitree_g1_23dof_ppo_teacher
  - /env/rewards: motion_tracking/rew_g1_23dof_stage2
  - /env/domain_randomization: domain_rand_base
  - /env/terrain: rough

project_name: HoloMotion

checkpoint: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250818_180528-train_g1_23dof_teacher_stage2_robodance100_ft_fix_origin/model_246500.pt
# checkpoint: /home/maiyue01.chen/project3/humanoid_locomotion/holomotion/logs/HoloMotion/20250818_180528-train_g1_23dof_teacher_stage2_robodance100_ft_fix_origin/model_246500.pt

motion_lmdb_path: /horizon-bucket/robot_lab/users/maiyue01.chen/lmdbs/lmdb_23dof_recorded_stand_squat

algo:
  algo:
    config:
      load_entropy_coef: false
      entropy_coef: 1.0e-3
      log_interval: 20
      save_interval: 500

rewards:
  reward_scales:
    penalty_action_smooth: -2.5

  l2_rel_tracking_keybody_pos_upper_weight: 0.3
  l2_rel_tracking_keybody_pos_lower_weight: 0.7

  l2_tracking_joint_pos_upper_weight: 0.3
  l2_tracking_joint_pos_lower_weight: 0.7

  l2_tracking_joint_vel_upper_weight: 0.3
  l2_tracking_joint_vel_lower_weight: 0.7

robot:
  asset:
    self_collisions: 1
  control:
    control_type: P

env:
  config:
    termination:
      terminate_by_gravity: true
      terminate_when_motion_far: true
      terminate_by_low_height: false

    termination_scales:
      termination_gravity_x: 0.8
      termination_gravity_y: 0.8
      termination_motion_far_threshold: 1.0
