# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: ppo_beyondmimic
  - /robot: unitree/G1/23dof/23dof_training_v0_official_urdf_beyondmimic_pd
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_beyondmimic_holostudent
  - /env/rewards: motion_tracking/rew_beyondmimic
  - /env/domain_randomization: domain_rand_beyondmimic
  - /env/terrain: plane

project_name: HoloMotion

# checkpoint: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250819_161849-train_g1_23dof_beyondmimic_holostudent/model_18000.pt

motion_lmdb_path: /horizon-bucket/robot_lab/users/maiyue01.chen/lmdbs/lmdb_lafan1_23dof
robot:
  motion:
    handpicked_motion_names: ["dance1_subject2_sliced-90-615_padded"]


rewards:
  reward_scales:
    falldown: -100


env:
  config:
    termination:
      terminate_by_gravity: true
      terminate_by_low_height: true
      terminate_when_ee_z_far: false
      terminate_when_motion_far: false
    termination_scales:
      terminate_when_ee_z_far_threshold: 0.25
      termination_min_base_height: 0.30
      termination_gravity_x: 0.7
      termination_gravity_y: 0.7

    noise_to_initial_level: 0
    init_noise_scale:
      dof_pos: 0.1
      dof_vel: 0.0
      root_pos: 0.05
      root_rot: 0.1
      root_vel: 0.5
      root_ang_vel: 0.5
