# @package _global_

defaults:
  - /training: train_base
  - /algo: ppo_isaaclab
  - /robot: unitree/G1/29dof/29dof_training_v0_official_urdf_beyondmimic_pd
  - /env: motion_tracking_isaaclab
  - /env/observations: motion_tracking/obs_unitree_g1_29dof_ppo_isaaclab
  - /env/rewards: motion_tracking/rew_g1_23dof_stage1
  - /env/domain_randomization: NO_domain_rand
  - /env/terrain: plane

project_name: HoloMotionLab
