# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: dagger_mlp
  - /robot: unitree/G1/23dof/23dof_training_v0_official_urdf
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_beyondmimic
  - /env/rewards: motion_tracking/rew_g1_23dof_stage2
  - /env/domain_randomization: domain_rand_base
  - /env/terrain: rough

project_name: HoloMotion

# checkpoint: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250815_192011-train_unitree_g1_23dof_student_robodance100_dagger_cs_mlp/model_23000.pt

# motion_lmdb_path: /horizon-bucket/robot_lab/users/maiyue01.chen/lmdbs/lmdb_robodance100_no_global_translation
motion_lmdb_path: /horizon-bucket/robot_lab/users/bo07.zhang/lmdbs/lmdb_g1_23dof_douyin0830_gvhmr_btws_pad_mpjpe266500_600

algo:
  algo:
    config:
      # teacher_actor_ckpt_path: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250818_180528-train_g1_23dof_teacher_stage2_robodance100_ft_fix_origin/model_246000.pt
      teacher_actor_ckpt_path: /horizon-bucket/robot_lab/users/bo07.zhang/expr_output/HoloMotion/HoloMotion/20250902_110256-train_g1_23dof_teacher_stage2_robodance100_ft_fix_origin/model_268000.pt
      use_teacher_rollout_annealing: true
