# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: dagger_mlp
  - /robot: unitree/G1/23dof/23dof_training_v0
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_unitree_g1_23dof_ppo_student.yaml
  - /env/rewards: motion_tracking/rew_g1_23dof_stage2
  - /env/domain_randomization: domain_rand_base
  - /env/terrain: rough

project_name: HoloMotion

checkpoint: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250815_192011-train_unitree_g1_23dof_student_robodance100_dagger_cs_mlp/model_23000.pt

motion_lmdb_path: /horizon-bucket/robot_lab/users/maiyue01.chen/lmdbs/lmdb_unitree_G1_23dof_robodance100

algo:
  algo:
    config:
      teacher_actor_ckpt_path: /horizon-bucket/robot_lab/users/maiyue01.chen/expr_output/HoloMotion/HoloMotion/20250813_164210-train_unitree_g1_23dof_teacher_stage2_robodance100_ft/model_276000.pt
      use_teacher_rollout_annealing: false