# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: dagger_transformer
  - /robot: unitree/G1/23dof/23dof_training_v0
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_unitree_g1_23dof_ppo_student
  - /env/rewards: motion_tracking/rew_g1_23dof_stage2
  - /env/domain_randomization: domain_rand_base
  - /env/terrain: rough

project_name: HoloMotion
